language: go
go:
  - 1.x
  - "1.10"
  - 1.11.x
  - master
script:
  - go build github.com/ma6254/FictionDown/cmd/FictionDown
notifications:
  email:
    recipients:
      - 1172380450@qq.com
      - 9a6c5609806a@gmail.com
      - ma6254ma@163.com
    on_success: change
    on_failure: always
